name: C++ CI Build

on:
  push:
    branches: [ "main", "features" ]
    paths-ignore:
      - '**.md'
      - '.gitignore'
  pull_request:
    branches: [ "main", "features" ]
    paths-ignore:
      - '**.md'
      - '.gitignore'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout local repository code
        uses: actions/checkout@v4

      # Setup MSYS2 and add its bin folder to PATH
      - name: Setup GCC (Windows only)
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: mingw-w64-ucrt-x86_64-gcc
          path-type: inherit

      - name: Compile the C++ main program
        working-directory: Projects/Part_2/lambda
        shell: bash
        run: g++ -std=c++23 -Os -s adder_by_lambda.cpp -o adder_by_lambda