name: C++26 Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Install Modern C++26 Compiler
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt-get update
          sudo apt-get install -y g++-14 gcc-14

      - name: Configure CMake Targets
        run: |
          cmake -B build \
            -DCMAKE_CXX_COMPILER=g++-14 \
            -DCMAKE_C_COMPILER=gcc-14

      - name: Build All Targets
        run: cmake --build build
